package jfilescontroller;

/*
 * Acerca.java
 *
 * Created on 24 de diciembre de 2007, 03:09 PM
 */

/**
 *
 * @author  SOLSISTEM
 */
public class Acerca extends javax.swing.JFrame {
    
    /** Creates new form Acerca */
    public Acerca() {
        initComponents();
        setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel2.setText("JFilesController");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 30, 130, 17);

        jLabel3.setText("Versión 1.0");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 60, 80, 14);

        jLabel4.setText("Plataforma: Java 1.6.0");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 90, 180, 14);

        jLabel5.setText("IDE: NetBeans 6.5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 120, 110, 14);

        jLabel6.setText("Tipo: Shareware");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(130, 150, 250, 14);

        jLabel8.setText("Fecha de creación: Sábado, 07 de Febrero del 2009");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(130, 180, 290, 14);

        jPanel1.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("SOLSISTEM (Soluciones para Sistemas Empresariales)");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(-20, 10, 500, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 280, 480, 60);

        jProgressBar1.setIndeterminate(true);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(0, 350, 490, 14);

        jLabel12.setText("Producto Hecho en Nicaragua por SOLSISTEM");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(130, 210, 320, 20);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Derechos Reservados @ 2009");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 260, 480, 20);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/JLogo.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(260, 30, 60, 100);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sologo.jpg"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 170, 100, 100);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/JFilesController.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 30, 100, 100);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-497)/2, (screenSize.height-389)/2, 497, 389);
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
    
}
