/*
 * JExp.java
 *
 * Created on 07 de octubre de 2008, 01:31 AM
 */

package jfilescontroller;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Francisco
 */
public class JExp extends javax.swing.JFrame
{    
    static boolean b = false;
    static int cont = 0;

    static DataInputStream leer;
    static DataOutputStream escribir;
    static File Fichero;

    static String pwd;
    
    /** Creates new form JExp */
    public JExp()
    {
        initComponents();
        setVisible(true);
        Abrir_Pwd();
    }

    public static void Entrada()
    {
        if(jPasswordField1.getText().equalsIgnoreCase(pwd))
        {
            b = true;
            JOptionPane.showMessageDialog(null, "Bienvenido a JFilesController", "Bienvenido", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Contraseña incorrecta","JFilesController",JOptionPane.WARNING_MESSAGE);
            jPasswordField1.setText("");
            jPasswordField1.requestFocus();
            b = false;
            cont++;
            if(cont == 3)
                System.exit(0);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.b
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Entrada");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Digite su contraseña:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 130, 14);

        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(20, 40, 290, 20);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 80, 80, 23);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(230, 80, 80, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Seguridad_ini.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 30, 50, 50);

        jButton3.setText("Cambiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(140, 220, 80, 23);

        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(230, 220, 80, 23);

        jLabel3.setText("Confirme su contraseña:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 120, 190, 14);

        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyPressed(evt);
            }
        });
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(20, 140, 290, 20);

        jLabel4.setText("Digite su nueva contraseña:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 170, 210, 14);

        jPasswordField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField3KeyPressed(evt);
            }
        });
        getContentPane().add(jPasswordField3);
        jPasswordField3.setBounds(20, 190, 290, 20);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-393)/2, (screenSize.height-142)/2, 393, 142);
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    Entrada();
    Principal.Verificar_Entrada();
    Principal.j.setVisible(false);
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    System.exit(0);
}//GEN-LAST:event_jButton2ActionPerformed

private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
// TODO add your handling code here:
    int KeyCode = evt.getKeyCode();
        
    if(KeyCode == 10)
    {
        Entrada();
        Principal.Verificar_Entrada();
    }
}//GEN-LAST:event_jPasswordField1KeyPressed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    // TODO add your handling code here:
    Cambiar_Pwd();
}//GEN-LAST:event_jButton3ActionPerformed

public static void Cambiar_Pwd()
{
    if(jPasswordField1.getText().equals(jPasswordField2.getText()))
    {
        leerFichero();

        if(jPasswordField1.getText().equalsIgnoreCase(pwd))
        {
            pwd = jPasswordField3.getText();
            Guardar_Pwd();
            JOptionPane.showMessageDialog(null, "La contraseña se ha cambiado satisfactoriamente", "JFilesController", JOptionPane.INFORMATION_MESSAGE);
            Principal.j.setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Contraseña incorrecta!", "Error", JOptionPane.ERROR_MESSAGE);
            Limpiar();
        }
    }
    else
    {
        JOptionPane.showMessageDialog(null, "Error al digitar su contraseña", "JFilesController", JOptionPane.ERROR_MESSAGE);
        Limpiar();
    }
}

public static void Limpiar()
{
    jPasswordField1.setText("");
    jPasswordField2.setText("");
    jPasswordField3.setText("");
    jPasswordField1.requestFocus();
}

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    // TODO add your handling code here:
    setVisible(false);
}//GEN-LAST:event_jButton4ActionPerformed

private void jPasswordField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyPressed
    // TODO add your handling code here:
}//GEN-LAST:event_jPasswordField2KeyPressed

private void jPasswordField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField3KeyPressed
    // TODO add your handling code here:
}//GEN-LAST:event_jPasswordField3KeyPressed

    public static void Guardar_Pwd()
    {
        Fichero = new File("jpwd.exe");

        /*if(!Fichero.exists())
        {
             JOptionPane.showMessageDialog(null,"Error, el programa necesita el archivo jpwd.exe","Error",JOptionPane.ERROR_MESSAGE);
             System.exit(0);
        }
        else
        {*/
            try
            {
                escribir = new DataOutputStream(new FileOutputStream(Fichero));
                escribirFichero();
            }
            catch(IOException ioException)
            {
            }
        //}
    }

    public static void escribirFichero()
    {
        String p;

        p = pwd;

        try
        {
            escribir.writeUTF(p);
            escribir.close();
        }
        catch(IOException io)
        {
            System.out.println("Error");
        }
    }

    public static void Abrir_Pwd()
    {
        Fichero = new File("jpwd.exe");

        if(!Fichero.exists())
        {
             JOptionPane.showMessageDialog(null,"Error, el programa necesita el archivo jpwd.exe","Error",JOptionPane.ERROR_MESSAGE);
             System.exit(0);
        }
        else
        {
            try
            {
                leer = new DataInputStream(new FileInputStream(Fichero));
                leerFichero();
            }
            catch(Exception e)
            {
            }
        }
    }

    public static void leerFichero()
    {
        String p;
        // abrir archivo
        try
        {
            p = leer.readUTF();
            pwd = p;
            leer.close();
        }
        catch(Exception e)
        {
            System.out.println("Error");
        }
    }

    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JExp().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton3;
    public static javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private static javax.swing.JPasswordField jPasswordField1;
    private static javax.swing.JPasswordField jPasswordField2;
    private static javax.swing.JPasswordField jPasswordField3;
    // End of variables declaration//GEN-END:variables

}
