/*
 * Principal.java
 *
 * Created on 29 de diciembre de 2008, 07:19 PM
 */

package jfilescontroller;

import java.awt.Component;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.awt.ScrollPane;
import javax.swing.event.*;

import java.io.*;
import java.util.*;

import javax.swing.table.*;

import java.awt.print.*;
import java.text.*;

import java.lang.Object;
import java.awt.Component;
import java.awt.Container;
import javax.swing.text.JTextComponent;

import javax.swing.*;

import jxl.write.WritableWorkbook;
import jxl.write.WritableSheet;
import jxl.write.Label;
import jxl.Workbook;
import jxl.write.WriteException;
import jxl.write.biff.WritableWorkbookImpl;
import org.omg.SendingContext.RunTimeOperations;

import java.awt.*;


/**
 *
 * @author  Yayi y Frank (SOLSISTEM)
 */
public class Principal extends javax.swing.JFrame 
{
    static Vector nuevafila;
    static DefaultTableModel modelotabla;
    static Vector nuevafila2;
    static DefaultTableModel modelotabla2;
    static int contador = 0;

    // Enviar a excel
    static WritableWorkbook  workbook = null;
    static WritableSheet sheet = null;
    static Label label = null;

    // Demo

    static int numero = 0;
    static DataInputStream leer3;
    static DataOutputStream escribir3;
    static boolean resp = true; // El programa expira cuando sea falso
    static File Fichero;

    conexion con = new conexion();
    ExecuteProcedure exe = new ExecuteProcedure(con);

    static JExp j;

    /** Creates new form Principal */
    public Principal() 
    {
        j.setVisible(false);
        setExtendedState(MAXIMIZED_BOTH);
        setIconImage(Cargar_Imagen("JFilesController_ico.png"));
        initComponents();
        this.jTextField1.setText("C");
        this.jTextField1.requestFocus();
        Invisible();
        Esperar_fin();
    }

    public static void Invisible()
    {
        jScrollPane3.setVisible(false);
        jTable3.setVisible(false);
        jScrollPane4.setVisible(false);
        jTable4.setVisible(false);
        jComboBox1.setVisible(false);
        jComboBox2.setVisible(false);
    }

    public void Respaldar_BD()
    {
        //ExecuteProcedure.Respaldar_BD("D:/archivo");
    }

    public static Image Cargar_Imagen(String FileName)
    {
        return Toolkit.getDefaultToolkit().getImage("src" + File.separator + "imagenes" + File.separator + FileName);
    }

    public void Listar_Archivos(String s)
    {
        this.Listar_Directorio(s);

        for(int k = 0; k < jComboBox1.getItemCount(); k++)
        {
            Agregar_Fila();
            jComboBox1.setSelectedIndex(k);
            jComboBox2.setSelectedIndex(k);
            jTable1.setValueAt(jComboBox1.getSelectedItem(), k, 0);
            jTable1.setValueAt(jComboBox2.getSelectedItem(), k, 1);
            //System.out.println(jComboBox1.getSelectedItem().toString());
        }

        this.jTextField3.setText(String.valueOf(contador));
    }

    private void Listar_Directorio(String dir)
    {
        File archivos = new File(dir);
        File[] lista = archivos.listFiles();

        Imprimir_Lista(lista);
    }
    
    private void Imprimir_Lista(File[] list)
    {
        for(int i = 0; i < list.length; i++)
        {
            if(!(list[i].isHidden()))
            {
                if(!(list[i].isDirectory()))
                {
                    //System.out.println(list[i].getName());
                    this.jComboBox1.addItem(list[i].getName());
                    this.jComboBox2.addItem(list[i].getPath());
                    contador++;
                }
                else
                {
                    Listar_Directorio(list[i].toString());
                }
            }
        }
    }
        
    public static void Agregar_Fila()
    {
        modelotabla = (DefaultTableModel) jTable1.getModel();
        nuevafila = new Vector();
        jTable1.setModel(modelotabla);
        nuevafila.add(null);
        modelotabla.addRow(nuevafila);
    }

    public static void Agregar_Fila2()
    {
        modelotabla2 = (DefaultTableModel) jTable2.getModel();
        nuevafila2 = new Vector();
        jTable2.setModel(modelotabla2);
        nuevafila2.add(null);
        modelotabla2.addRow(nuevafila2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JFilesController");
        setResizable(false);
        getContentPane().setLayout(null);

        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(30, 740, 28, 20);

        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(30, 740, 28, 20);

        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre del archivo", "Directorio del archivo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 920, 400);

        jLabel1.setText("Nombre de la unidad:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 4, 200, 30);

        jLabel2.setText("Nombre marcado sobre la unidad:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 40, 200, 20);

        jLabel3.setText("Cantidad de archivos:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 74, 200, 20);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(250, 10, 110, 20);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(250, 40, 220, 20);

        jButton1.setText("Escanear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(370, 10, 100, 23);

        jTextField3.setEditable(false);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(250, 70, 110, 20);

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(370, 70, 100, 23);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Esperar.png"))); // NOI18N
        jLabel6.setText("Por favor espere...");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(500, 20, 160, 70);

        jProgressBar1.setIndeterminate(true);
        jPanel1.add(jProgressBar1);
        jProgressBar1.setBounds(550, 70, 146, 14);

        jTabbedPane1.addTab("Recopilación de archivos", jPanel1);

        jPanel2.setLayout(null);

        jLabel4.setText("Nombre del archivo:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 20, 140, 20);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField4);
        jTextField4.setBounds(250, 20, 220, 20);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Nombre del archivo", "Directorio del archivo", "Etiqueta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jTable2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable2FocusGained(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(20, 80, 920, 430);

        jButton4.setText("Borrar todo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(820, 50, 110, 23);

        jLabel5.setText("Cantidad de archivos:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 50, 200, 20);

        jTextField5.setEditable(false);
        jPanel2.add(jTextField5);
        jTextField5.setBounds(250, 50, 110, 20);

        jButton5.setText("Borrar unidad");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(700, 50, 110, 23);

        jButton6.setText("Borrar archivo");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(480, 50, 150, 23);

        jTabbedPane1.addTab("Búsqueda de archivos", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(20, 70, 970, 590);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Nombre del archivo", "Directorio del archivo"}
            },
            new String [] {
                "Nombre del archivo", "Directorio del archivo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(330, 740, 220, 70);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"No.", "Nombre del archivo", "Directorio del archivo", "Etiqueta"}
            },
            new String [] {
                "No.", "Nombre del archivo", "Directorio del archivo", "Etiqueta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(90, 740, 220, 70);

        jToolBar1.setRollover(true);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Escanear.png"))); // NOI18N
        jButton10.setToolTipText("Escanear");
        jButton10.setFocusable(false);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton10);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Guardar.png"))); // NOI18N
        jButton11.setToolTipText("Guardar");
        jButton11.setFocusable(false);
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton11);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Buscar.png"))); // NOI18N
        jButton12.setToolTipText("Buscar");
        jButton12.setFocusable(false);
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton12);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Limpiar.png"))); // NOI18N
        jButton13.setToolTipText("Limpiar");
        jButton13.setFocusable(false);
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton13);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Excel.png"))); // NOI18N
        jButton14.setToolTipText("Exportar a Excel");
        jButton14.setFocusable(false);
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton14);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Seguridad_pwd.png"))); // NOI18N
        jButton15.setToolTipText("Cambiar contraseña");
        jButton15.setFocusable(false);
        jButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton15);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Instalar.png"))); // NOI18N
        jButton16.setToolTipText("Instalar Foxit Reader");
        jButton16.setFocusable(false);
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton16);

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Calculadora.png"))); // NOI18N
        jButton17.setToolTipText("Calculadora");
        jButton17.setFocusable(false);
        jButton17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton17.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton17);

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salir.png"))); // NOI18N
        jButton18.setToolTipText("Salir");
        jButton18.setFocusable(false);
        jButton18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton18.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton18);

        getContentPane().add(jToolBar1);
        jToolBar1.setBounds(0, 0, 1290, 60);

        jMenu1.setText("Recopilación");

        jMenuItem1.setText("Escanear");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Guardar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Búsqueda");

        jMenuItem3.setText("Buscar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenu7.setText("Borrar");

        jMenuItem4.setText("Archivo");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem4);

        jMenuItem5.setText("Unidad");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem5);

        jMenuItem6.setText("Todo");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem6);

        jMenu2.add(jMenu7);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Seguridad");

        jMenuItem9.setText("Cambiar contraseña");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Herramientas");

        jMenuItem10.setText("Calculadora");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuItem11.setText("Foxit Reader");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenuItem14.setText("Exportar a Excel");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem14);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Ayuda");

        jMenuItem12.setText("Contenido");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem12);

        jMenuItem13.setText("Contacto");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem13);

        jMenuItem7.setText("Acerca de...");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Salir");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1023)/2, (screenSize.height-874)/2, 1023, 874);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Escanear();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void Esperar_ini()
    {
        this.jLabel6.setVisible(true);
        this.jProgressBar1.setVisible(true);
    }

    public void Esperar_fin()
    {
        this.jLabel6.setVisible(false);
        this.jProgressBar1.setVisible(false);
    }

    public void Escanear()
    {
        try
        {
            Esperar_ini();
            JOptionPane.showMessageDialog(null, "El escaneo puede durar un tiempo severo", "JFilesController", JOptionPane.INFORMATION_MESSAGE);
            Limpiar_Tabla();
            Listar_Archivos(this.jTextField1.getText() + ":");
            jTextField2.requestFocus();
            Esperar_fin();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error al escanear", "Error", JOptionPane.ERROR_MESSAGE);
            Esperar_fin();
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Guardar();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void Guardar()
    {
        Esperar_ini();
        JOptionPane.showMessageDialog(null, "Este proceso puede durar un tiempo severo", "JFilesController", JOptionPane.INFORMATION_MESSAGE);
        Guardar_Informacion();
        jTabbedPane1.setSelectedIndex(1);
        jTextField4.requestFocus();
        Esperar_fin();
    }

    public void Buscar_Archivo(String nom)
    {
        exe.addRowData(jTable2, "select * from detalle_unidad where Nombre like '%" + nom + "%';");
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Borrar_Todo();
    }//GEN-LAST:event_jButton4ActionPerformed

    public void Borrar_Todo()
    {
        int result = JOptionPane.showConfirmDialog((Component)null,"Esta seguro que desea eliminar todo?","JFilesController",JOptionPane.YES_NO_OPTION);

        if(result == JOptionPane.YES_OPTION)
        {
            ExecuteProcedure.Borrar_Todo();
        }
    }

    private void jTable2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2FocusGained

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        Buscar_CD();
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Borrar_Archivo();
    }//GEN-LAST:event_jButton6ActionPerformed

    public void Borrar_Archivo()
    {
        int result = JOptionPane.showConfirmDialog((Component)null,"Esta seguro que desea eliminar el archivo seleccionado?","JFilesController",JOptionPane.YES_NO_OPTION);

        if(result == JOptionPane.YES_OPTION)
        {
            int r = jTable2.getSelectedRow();
            exe.Borrar_Archivo(String.valueOf(jTable2.getValueAt(r, 1)), String.valueOf(jTable2.getValueAt(r, 3)));
        }
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Borrar_Unidad();
    }//GEN-LAST:event_jButton5ActionPerformed

    public void Borrar_Unidad()
    {
        int result = JOptionPane.showConfirmDialog((Component)null,"Esta seguro que desea eliminar la unidad seleccionada?","JFilesController",JOptionPane.YES_NO_OPTION);

        if(result == JOptionPane.YES_OPTION)
        {
            int r = jTable2.getSelectedRow();
            exe.Borrar_Unidad(String.valueOf(jTable2.getValueAt(r, 3)));
        }
    }

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        // TODO add your handling code here:
        Buscar();
    }//GEN-LAST:event_jTextField4KeyPressed

    public void Buscar()
    {
        try
        {
            Limpiar_Tabla2();
            Buscar_Archivo(jTextField4.getText());
        }
        catch(Exception e)
        {
        }
    }

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.jTabbedPane1.setSelectedIndex(0);
        Escanear();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.jTabbedPane1.setSelectedIndex(0);
        Guardar();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.jTabbedPane1.setSelectedIndex(1);
        Buscar();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        this.jTabbedPane1.setSelectedIndex(1);
        Borrar_Archivo();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        this.jTabbedPane1.setSelectedIndex(1);
        Borrar_Unidad();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        this.jTabbedPane1.setSelectedIndex(1);
        Borrar_Todo();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        this.Llamar_Calculadora();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        this.Instalar_FoxitReader();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        this.Exportar();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        this.Exportar();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        this.Escanear();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        this.Guardar();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        this.Buscar();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        this.Limpiar_Todo();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        this.Instalar_FoxitReader();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        this.Llamar_Calculadora();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here
        this.Salir();
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        Cambiar_Contraseña();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
        // TODO add your handling code here:
        //this.Salir();
    }//GEN-LAST:event_jMenu6ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        this.Cambiar_Contraseña();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        this.Abrir_Ayuda();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        // TODO add your handling code here:
        this.Salir();
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Para mayor información o cualquier sugerencia: \n\n - Jahaira José Mena Soza (jahairamena@gmail.com) \n - José Francisco Rodríguez Chávez (ingenierojosefrancisco@gmail.com)", "Contacto", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        Acerca acerca = new Acerca();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    public void Abrir_Ayuda()
    {
        try
        {
    		Runtime rt = Runtime.getRuntime();
    		Process p = rt.exec("AbrirAyuda.bat");
    		p.waitFor();
    	}
    	catch(Exception e)
    	{
    	}
    }

    public static void Cambiar_Contraseña()
    {
        j.setVisible(true);
        j.setSize(393, 305);
        j.jButton1.setVisible(false);
        j.jButton2.setVisible(false);
        j.Limpiar();
    }

    public void Salir()
    {
        int result = JOptionPane.showConfirmDialog((Component)null,"Esta seguro que desea salir?","JFilesController",JOptionPane.YES_NO_OPTION);

        if(result == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }

    public void Limpiar_Todo()
    {
        this.Limpiar_Tabla();
        this.Limpiar_Tabla2();
        this.jTextField1.setText("");
        this.jTextField2.setText("");
        this.jTextField3.setText("");
        this.jTextField4.setText("");
        this.jTextField5.setText("");
        this.jTabbedPane1.setSelectedIndex(0);
        this.jTextField1.requestFocus();
        this.contador = 0;
        this.jComboBox1.removeAllItems();
        this.jComboBox2.removeAllItems();
    }

    public void Llamar_Calculadora()
    {
        try
        {
    		Runtime rt = Runtime.getRuntime();
    		Process p = rt.exec("Calc.exe");
    		p.waitFor();
    	}
    	catch(Exception e)
    	{
    	}
    }

    public void Instalar_FoxitReader()
    {
        try
        {
            Runtime rt = Runtime.getRuntime();
            Process p = rt.exec("Instalar_FoxitReader.bat");
            p.waitFor();
        }
        catch(Exception e)
        {
        }
    }

    public void Exportar()
    {
        if(this.jTabbedPane1.getSelectedIndex() == 0)
        {
            Exportar_Tabla1();
        }
        else
        {
            Exportar_Tabla2();
        }
    }

    public void Exportar_Tabla1()
    {
        try
        {
            CrearExcel("Libro1.xls","Hoja1",jTable1.getModel(), jTable3.getModel());
            Runtime.getRuntime().exec("AbrirExcel.bat");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error al exportar","Error",JOptionPane.ERROR_MESSAGE);
        }
    }

    public void Exportar_Tabla2()
    {
        try
        {
            CrearExcel("Libro2.xls","Hoja1",jTable2.getModel(),jTable4.getModel());
            Runtime.getRuntime().exec("AbrirExcel2.bat");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error al exportar","Error",JOptionPane.ERROR_MESSAGE);
        }
    }

    public static void CrearExcel(String ruta,String nombreHoja,TableModel modeloTabla,TableModel modeloTabla2){

    try
    {
        workbook = Workbook.createWorkbook(new File(ruta));
        sheet = workbook.createSheet(nombreHoja,0);

        for(int i=0;i<modeloTabla2.getRowCount();i++)
        {
            for(int j=0;j<modeloTabla2.getColumnCount();j++)
            {
                Object x = modeloTabla2.getValueAt(i,j);

                if(x!=null)
                    label = new Label(j,i,x.toString());
                else
                    label = new Label(j,i,"");

                sheet.addCell(label);
            }
        }

        for(int i=0;i<modeloTabla.getRowCount();i++)
        {
            for(int j=0;j<modeloTabla.getColumnCount();j++)
            {
                Object x = modeloTabla.getValueAt(i,j);

                if(x!=null)
                    label = new Label(j,i + 1,x.toString());
                else
                    label = new Label(j,i + 1,"");

                sheet.addCell(label);
            }
        }

        workbook.write();
        workbook.close();
    }
    catch(IOException e){
        JOptionPane.showMessageDialog(null,e.toString(),"Error",JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    catch(WriteException e){
        JOptionPane.showMessageDialog(null,e.toString(),"Error",JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    }

    public void Buscar_CD()
    {
        int r = jTable2.getSelectedRow();
        //System.out.println(r);
        jTextField5.setText(exe.Mostrar_Cantidad_Archivos(r));
    }

    public void Guardar_Informacion()
    {
        try
        {
            String nom = "", dir = "", eti = "";

            eti = this.jTextField2.getText();
            
            exe.FillRowData(jTable1, eti, contador);

            for(int k = 0; k < jComboBox1.getItemCount(); k++)
            {
                jComboBox1.setSelectedIndex(k);
                jComboBox2.setSelectedIndex(k);
                nom = jComboBox1.getSelectedItem().toString();
                dir = jComboBox2.getSelectedItem().toString();
            }

            JOptionPane.showMessageDialog(null, "Todos los archivos de la unidad: " + this.jTextField1.getText() + " se han registrado satisfactoriamente");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error al guardar información", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void Eliminar_Fila()
    {
        int fila = jTable1.getRowCount() - 1;
        modelotabla.removeRow(fila);
    }

    public void Eliminar_Accion()
    {
        try
        {
            int f = 0;

            f = jTable1.getSelectedRow();

            int result = JOptionPane.showConfirmDialog((Component)null,"Esta seguro que desea eliminar la fila seleccionada?","JConsolidado",JOptionPane.YES_NO_OPTION);

            if(result == JOptionPane.YES_OPTION)
            {
                modelotabla.removeRow(f);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Debe seleccionar una fila","Error",JOptionPane.ERROR_MESSAGE);
        }
    }

    public static void Limpiar_Tabla()
    {
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre del archivo", "Directorio del archivo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        contador = 0;
        jComboBox1.removeAllItems(); // Nombre del archivo
        jComboBox2.removeAllItems(); // Directorio del archivo
    }

    public static void Limpiar_Tabla2()
    {
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Nombre del archivo", "Directorio del archivo", "Etiqueta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {

                // Aplicar HiFiLookAndFeel a nuestra aplicación
                try
                {
                    UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
                }
                catch(Exception e)
                {
                        try
                        {
                            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                        }
                        catch(Exception err)
                        {
                            System.out.println("Error loading myXPStyleTheme: " + err.toString());
                        }
                }

                j = new JExp();
            }
        });
        //JPositionRating valuacion = new JPositionRating();
        //valuacion.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    public static void Verificar_Entrada()
    {
        if(JExp.b == true)
        {
            new Principal().setVisible(true);
        }
        else
        {
        }
    }

    public static boolean Fecha_Expiracion()
    {
        Date hoy = new Date();
        Date fecha = new Date();

        fecha.setYear(2030); // Esta es la fecha de expiración.

        //System.out.println(hoy.getYear() + 1900);
        //System.out.println(fecha.getYear());

        if((hoy.getYear() + 1900) >= fecha.getYear())
        {
            return true;
        }
        else
        {
            return false;
        }
    }

    public static void Final()
    {
        JOptionPane.showMessageDialog(null,"El programa ha expirado, si desea comprarlo envíe un mensaje a: ingenierojosefrancisco@gmail.com","JConsolidado",JOptionPane.ERROR_MESSAGE);
        System.exit(0);
    }

    public static void Expiracion()
    {
        Fichero = new File("Config.exe");

        if(!Fichero.exists())
        {
             JOptionPane.showMessageDialog(null,"Error, el programa necesita el archivo Config.exe","Error",JOptionPane.ERROR_MESSAGE);
             System.exit(0);
        }
        else
        {
             if(Demostrar() == false)
             {
                  Final();
             }
             else
             {
                  new Principal().setVisible(true);
             }
        }
    }

    public static boolean Demostrar()
    {
        Fichero = new File("Config.exe");

	leerFichero3();
	escribirFichero3();

	return condicionar();
    }

    public static void leerFichero3()
    {
	// abrir archivo
	try
	{
		leer3 = new DataInputStream(new FileInputStream(Fichero));
		int num;

		num = leer3.readInt();
		numero = num;

                System.out.println(String.valueOf(numero));

		leer3.close();
	}

	// procesa la excepcion al abrir el archivo
	catch(Exception e)
	{
		//JOptionPane.showMessageDialog(this,"Error al abrir el archivo","Error",JOptionPane.ERROR_MESSAGE);
	}
    }

    public static void escribirFichero3()
    {
	try
	{
		escribir3 = new DataOutputStream(new FileOutputStream(Fichero));
		int num = numero;

		num = 2; //num + 1;

		escribir3.writeInt(num);
		escribir3.close();
	}
	// mostrar mensaje de error si no se puede abrir el archivo
	catch(IOException ioException)
	{
		//JOptionPane.showMessageDialog(this,"Error al abrir el archivo","Error",JOptionPane.ERROR_MESSAGE);
	}
    }

    public static boolean condicionar()
    {
        System.out.println("Limite: 3");

	if(numero >= 3)
		return false;
	else
		return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private static javax.swing.JComboBox jComboBox1;
    private static javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JScrollPane jScrollPane3;
    private static javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private static javax.swing.JTable jTable1;
    public static javax.swing.JTable jTable2;
    private static javax.swing.JTable jTable3;
    private static javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private static javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

}
